package exceptions.task2;

public class Main {
}
